#!/usr/bin/env python3
"""Build, sign, inspect, and transmit OV-Watch recovery OTA packages."""

from __future__ import annotations

import argparse
import getpass
import hashlib
import pathlib
import re
import struct
import sys
import time
import zlib

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import (
    decode_dss_signature,
    encode_dss_signature,
)

MANIFEST_MAGIC = 0x314D564F
MANIFEST_FORMAT = 1
MANIFEST_SIZE = 128
TARGET_ID = 0xF411CE01
APPLICATION_ADDRESS = 0x08011000
APPLICATION_MAX_SIZE = 0x08080000 - APPLICATION_ADDRESS
VALID_MARKER = 0x51A7B007
ERASED_MARKER = 0xFFFFFFFF
CHUNK_MAGIC = 0x4843564F
CHUNK_SIZE = 256
SYNC = b"OVOTA1\r\n"

PREFIX_FORMAT = "<IHHIIII32s"
PREFIX_SIZE = struct.calcsize(PREFIX_FORMAT)
MANIFEST_FORMAT_STRUCT = "<IHHIIII32s64sII"
DEFAULT_PUBLIC_HEADER = pathlib.Path(__file__).resolve().parents[1] / "Inc" / "ota_public_key.h"


def read_password(prompt: str) -> bytes | None:
    password = getpass.getpass(prompt)
    return password.encode("utf-8") if password else None


def write_public_header(public_key: ec.EllipticCurvePublicKey,
                        output: pathlib.Path) -> None:
    numbers = public_key.public_numbers()
    raw = numbers.x.to_bytes(32, "big") + numbers.y.to_bytes(32, "big")
    lines = []
    for index in range(0, len(raw), 8):
        lines.append("    " + ", ".join(f"0x{value:02X}U" for value in raw[index:index + 8]) + ",")
    output.write_text(
        "#ifndef OTA_PUBLIC_KEY_H\n"
        "#define OTA_PUBLIC_KEY_H\n\n"
        "#include <stdint.h>\n\n"
        "/* ECDSA-P256 public key generated by ota_tool.py; raw X || Y. */\n"
        "static const uint8_t g_ota_public_key_p256[64] = {\n"
        + "\n".join(lines)
        + "\n};\n\n#endif /* OTA_PUBLIC_KEY_H */\n",
        encoding="utf-8",
    )


def command_keygen(args: argparse.Namespace) -> None:
    private_path = pathlib.Path(args.private_key).resolve()
    public_header = pathlib.Path(args.public_header).resolve()
    if private_path.exists():
        raise SystemExit(f"Refusing to overwrite existing private key: {private_path}")
    private_path.parent.mkdir(parents=True, exist_ok=True)
    public_header.parent.mkdir(parents=True, exist_ok=True)

    password = (None if args.no_password else
                read_password("New private-key passphrase (empty = unencrypted): "))
    encryption = (serialization.BestAvailableEncryption(password)
                  if password else serialization.NoEncryption())
    private_key = ec.generate_private_key(ec.SECP256R1())
    private_path.write_bytes(private_key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        encryption,
    ))
    write_public_header(private_key.public_key(), public_header)
    print(f"Private key: {private_path}")
    print(f"Public header: {public_header}")
    print("Back up the private key. Losing it requires reflashing the bootloader by ST-Link.")


def load_private_key(path: pathlib.Path,
                     no_password: bool = False) -> ec.EllipticCurvePrivateKey:
    data = path.read_bytes()
    password = (None if no_password else
                read_password("Private-key passphrase (empty if unencrypted): "))
    key = serialization.load_pem_private_key(data, password=password)
    if not isinstance(key, ec.EllipticCurvePrivateKey) or not isinstance(key.curve, ec.SECP256R1):
        raise SystemExit("The signing key must be an ECDSA P-256 private key")
    return key


def validate_vector(image: bytes) -> None:
    if len(image) < 8:
        raise SystemExit("Application binary is too small to contain a vector table")
    stack_pointer, reset_handler = struct.unpack_from("<II", image, 0)
    if not (0x20000000 <= stack_pointer <= 0x20020000):
        raise SystemExit(f"Invalid initial MSP 0x{stack_pointer:08X}; is the app linked at 0x08011000?")
    reset_address = reset_handler & ~1
    if not (reset_handler & 1):
        raise SystemExit("Reset handler is not a Thumb address")
    if not (APPLICATION_ADDRESS <= reset_address < APPLICATION_ADDRESS + len(image)):
        raise SystemExit(
            f"Reset handler 0x{reset_handler:08X} is outside the relocated image; "
            "rebuild the application at 0x08011000"
        )


def verify_manifest_signature(manifest: bytes,
                              public_header: pathlib.Path = DEFAULT_PUBLIC_HEADER) -> None:
    """Verify the raw r||s signature using the public key compiled into the bootloader."""
    header_text = public_header.read_text(encoding="utf-8")
    raw_public_key = bytes(int(value, 16) for value in
                           re.findall(r"0x([0-9A-Fa-f]{2})U", header_text))
    if len(raw_public_key) != 64:
        raise SystemExit(f"Expected 64 public-key bytes in {public_header}")

    x_value = int.from_bytes(raw_public_key[:32], "big")
    y_value = int.from_bytes(raw_public_key[32:], "big")
    public_key = ec.EllipticCurvePublicNumbers(
        x_value, y_value, ec.SECP256R1()
    ).public_key()
    signature = manifest[PREFIX_SIZE:PREFIX_SIZE + 64]
    signature_der = encode_dss_signature(
        int.from_bytes(signature[:32], "big"),
        int.from_bytes(signature[32:], "big"),
    )
    try:
        public_key.verify(signature_der, manifest[:PREFIX_SIZE],
                          ec.ECDSA(hashes.SHA256()))
    except InvalidSignature as exc:
        raise SystemExit("Manifest ECDSA-P256 signature is invalid") from exc


def build_manifest(image: bytes, version: int,
                   private_key: ec.EllipticCurvePrivateKey) -> bytes:
    digest = hashlib.sha256(image).digest()
    prefix = struct.pack(
        PREFIX_FORMAT,
        MANIFEST_MAGIC,
        MANIFEST_FORMAT,
        MANIFEST_SIZE,
        TARGET_ID,
        version,
        len(image),
        APPLICATION_ADDRESS,
        digest,
    )
    if len(prefix) != PREFIX_SIZE or PREFIX_SIZE != 56:
        raise AssertionError("Manifest prefix layout changed")
    signature_der = private_key.sign(prefix, ec.ECDSA(hashes.SHA256()))
    r_value, s_value = decode_dss_signature(signature_der)
    signature = r_value.to_bytes(32, "big") + s_value.to_bytes(32, "big")
    header_without_crc = prefix + signature
    header_crc = zlib.crc32(header_without_crc) & 0xFFFFFFFF
    manifest = header_without_crc + struct.pack("<II", header_crc, ERASED_MARKER)
    if len(manifest) != MANIFEST_SIZE:
        raise AssertionError("Manifest must be exactly 128 bytes")
    return manifest


def command_pack(args: argparse.Namespace) -> None:
    image_path = pathlib.Path(args.bin).resolve()
    output_path = pathlib.Path(args.output).resolve()
    image = image_path.read_bytes()
    if len(image) > APPLICATION_MAX_SIZE:
        raise SystemExit(
            f"Image is {len(image)} bytes; maximum is {APPLICATION_MAX_SIZE} bytes"
        )
    validate_vector(image)
    private_key = load_private_key(pathlib.Path(args.private_key).resolve(),
                                   args.no_password)
    manifest = build_manifest(image, args.version, private_key)
    output_path.write_bytes(manifest + image)
    print(f"Package: {output_path}")
    print(f"Version: {args.version}")
    print(f"Image bytes: {len(image)}")
    print(f"SHA-256: {hashlib.sha256(image).hexdigest()}")


def ihex_record(address: int, record_type: int, payload: bytes) -> str:
    """生成一行 Intel HEX，并计算二进制补码校验和。"""
    body = bytes((len(payload),)) + struct.pack(">H", address) + bytes((record_type,)) + payload
    checksum = (-sum(body)) & 0xFF
    return ":" + (body + bytes((checksum,))).hex().upper()


def read_ihex(path: pathlib.Path) -> dict[int, int]:
    """读取 Keil 生成的 Intel HEX，只展开实际数据字节。"""
    memory: dict[int, int] = {}
    upper_address = 0

    for line_number, raw_line in enumerate(path.read_text(encoding="ascii").splitlines(), 1):
        line = raw_line.strip()
        if not line:
            continue
        if not line.startswith(":"):
            raise SystemExit(f"Invalid Intel HEX line {line_number} in {path}")
        try:
            record = bytes.fromhex(line[1:])
        except ValueError as exc:
            raise SystemExit(f"Invalid hexadecimal data on line {line_number}") from exc
        if len(record) < 5 or len(record) != record[0] + 5 or (sum(record) & 0xFF) != 0:
            raise SystemExit(f"Invalid Intel HEX checksum or length on line {line_number}")

        count = record[0]
        offset = struct.unpack_from(">H", record, 1)[0]
        record_type = record[3]
        payload = record[4:4 + count]
        if record_type == 0x00:
            absolute = upper_address + offset
            for index, value in enumerate(payload):
                address = absolute + index
                previous = memory.get(address)
                if previous is not None and previous != value:
                    raise SystemExit(f"Conflicting HEX data at 0x{address:08X}")
                memory[address] = value
        elif record_type == 0x01:
            break
        elif record_type == 0x02:
            if count != 2:
                raise SystemExit("Invalid extended-segment-address record")
            upper_address = int.from_bytes(payload, "big") << 4
        elif record_type == 0x04:
            if count != 2:
                raise SystemExit("Invalid extended-linear-address record")
            upper_address = int.from_bytes(payload, "big") << 16
        elif record_type not in (0x03, 0x05):
            raise SystemExit(f"Unsupported Intel HEX record type 0x{record_type:02X}")
    return memory


def add_memory_region(memory: dict[int, int], address: int,
                      payload: bytes, name: str) -> None:
    for index, value in enumerate(payload):
        current_address = address + index
        if current_address in memory and memory[current_address] != value:
            raise SystemExit(
                f"{name} overlaps different data at 0x{current_address:08X}"
            )
        memory[current_address] = value


def write_ihex(path: pathlib.Path, memory: dict[int, int]) -> None:
    """按地址排序输出 16 字节数据记录，便于 ST-Link/Keil 直接烧录。"""
    addresses = sorted(memory)
    lines: list[str] = []
    index = 0
    current_upper = None

    while index < len(addresses):
        start = addresses[index]
        upper = start >> 16
        if upper != current_upper:
            lines.append(ihex_record(0, 0x04, struct.pack(">H", upper)))
            current_upper = upper

        chunk = bytearray((memory[start],))
        index += 1
        while (index < len(addresses) and len(chunk) < 16 and
               addresses[index] == start + len(chunk) and
               (addresses[index] >> 16) == upper):
            chunk.append(memory[addresses[index]])
            index += 1
        lines.append(ihex_record(start & 0xFFFF, 0x00, bytes(chunk)))

    lines.append(ihex_record(0, 0x01, b""))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def command_factory(args: argparse.Namespace) -> None:
    """生成首次安装用的 Bootloader + 已提交清单 + 应用组合 HEX。"""
    boot_hex = pathlib.Path(args.boot_hex).resolve()
    image_path = pathlib.Path(args.bin).resolve()
    output_path = pathlib.Path(args.output).resolve()
    image = image_path.read_bytes()
    if len(image) > APPLICATION_MAX_SIZE:
        raise SystemExit(
            f"Image is {len(image)} bytes; maximum is {APPLICATION_MAX_SIZE} bytes"
        )
    validate_vector(image)

    private_key = load_private_key(pathlib.Path(args.private_key).resolve(),
                                   args.no_password)
    transport_manifest = build_manifest(image, args.version, private_key)
    committed_manifest = transport_manifest[:-4] + struct.pack("<I", VALID_MARKER)
    verify_manifest_signature(committed_manifest)

    memory = read_ihex(boot_hex)
    if not memory:
        raise SystemExit("Bootloader HEX contains no data")
    if min(memory) < 0x08000000 or max(memory) >= 0x08010000:
        raise SystemExit("Bootloader HEX is outside its reserved 64 KiB region")
    add_memory_region(memory, 0x08010000, committed_manifest, "Manifest")
    add_memory_region(memory, APPLICATION_ADDRESS, image, "Application")
    write_ihex(output_path, memory)

    # 回读生成文件，避免把格式损坏的 HEX 交给烧录器。
    written = read_ihex(output_path)
    if (bytes(written[0x08010000 + index] for index in range(MANIFEST_SIZE)) !=
            committed_manifest):
        raise SystemExit("Factory HEX manifest read-back verification failed")
    if (bytes(written[APPLICATION_ADDRESS + index] for index in range(len(image))) != image):
        raise SystemExit("Factory HEX application read-back verification failed")

    print(f"Factory HEX: {output_path}")
    print(f"Version: {args.version}")
    print(f"Application bytes: {len(image)}")
    print("Contains bootloader, committed signed manifest, and relocated application.")


def command_apphex(args: argparse.Namespace) -> None:
    """生成单独更新主应用时使用的“签名清单 + 应用”HEX。"""
    image_path = pathlib.Path(args.bin).resolve()
    output_path = pathlib.Path(args.output).resolve()
    image = image_path.read_bytes()
    if len(image) > APPLICATION_MAX_SIZE:
        raise SystemExit(
            f"Image is {len(image)} bytes; maximum is {APPLICATION_MAX_SIZE} bytes"
        )
    validate_vector(image)
    private_key = load_private_key(pathlib.Path(args.private_key).resolve(),
                                   args.no_password)
    transport_manifest = build_manifest(image, args.version, private_key)
    committed_manifest = transport_manifest[:-4] + struct.pack("<I", VALID_MARKER)
    verify_manifest_signature(committed_manifest)

    memory: dict[int, int] = {}
    add_memory_region(memory, 0x08010000, committed_manifest, "Manifest")
    add_memory_region(memory, APPLICATION_ADDRESS, image, "Application")
    write_ihex(output_path, memory)
    written = read_ihex(output_path)
    if (bytes(written[APPLICATION_ADDRESS + index] for index in range(len(image))) != image):
        raise SystemExit("Signed application HEX read-back verification failed")
    print(f"Signed application HEX: {output_path}")
    print(f"Version: {args.version}")
    print(f"Application bytes: {len(image)}")
    print("Contains committed signed manifest and relocated application; no bootloader.")


def parse_package(path: pathlib.Path) -> tuple[bytes, bytes, tuple]:
    package = path.read_bytes()
    if len(package) < MANIFEST_SIZE:
        raise SystemExit("Package is shorter than its manifest")
    manifest = package[:MANIFEST_SIZE]
    fields = struct.unpack(MANIFEST_FORMAT_STRUCT, manifest)
    magic, fmt, header_size, target, version, image_size, address, digest, signature, crc, marker = fields
    if (magic, fmt, header_size, target, address) != (
        MANIFEST_MAGIC, MANIFEST_FORMAT, MANIFEST_SIZE, TARGET_ID, APPLICATION_ADDRESS
    ):
        raise SystemExit("Package manifest target or format is invalid")
    if marker != ERASED_MARKER:
        raise SystemExit("Transport package must carry an erased valid marker")
    if zlib.crc32(manifest[:120]) & 0xFFFFFFFF != crc:
        raise SystemExit("Manifest CRC32 mismatch")
    verify_manifest_signature(manifest)
    image = package[MANIFEST_SIZE:]
    if len(image) != image_size:
        raise SystemExit(f"Package image length mismatch: header={image_size}, actual={len(image)}")
    if hashlib.sha256(image).digest() != digest:
        raise SystemExit("Package image SHA-256 mismatch")
    validate_vector(image)
    return manifest, image, fields


def command_inspect(args: argparse.Namespace) -> None:
    _manifest, image, fields = parse_package(pathlib.Path(args.package).resolve())
    print(f"Version: {fields[4]}")
    print(f"Image address: 0x{fields[6]:08X}")
    print(f"Image bytes: {len(image)}")
    print(f"SHA-256: {fields[7].hex()}")


def read_exact(serial_port, length: int) -> bytes:
    result = bytearray()
    deadline = time.monotonic() + max(5.0, serial_port.timeout or 0.0)
    while len(result) < length:
        data = serial_port.read(length - len(result))
        if data:
            result.extend(data)
            continue
        if time.monotonic() >= deadline:
            raise TimeoutError(f"Timed out waiting for {length} bytes")
    return bytes(result)


def read_status(serial_port) -> tuple[bytes, int]:
    frame = read_exact(serial_port, 8)
    return frame[:4], struct.unpack_from("<I", frame, 4)[0]


def expect_status(serial_port, expected: bytes) -> int:
    tag, value = read_status(serial_port)
    if tag == b"FAIL":
        raise RuntimeError(f"Bootloader rejected the operation, error code {value}")
    if tag != expected:
        raise RuntimeError(f"Expected {expected!r}, received {tag!r} value={value}")
    return value


def command_send(args: argparse.Namespace) -> None:
    try:
        import serial
    except ImportError as exc:
        raise SystemExit("Install pyserial first: python -m pip install pyserial") from exc

    manifest, image, fields = parse_package(pathlib.Path(args.package).resolve())
    with serial.Serial(args.port, 9600, timeout=90, write_timeout=30) as port:
        port.reset_input_buffer()
        port.write(SYNC)
        port.flush()
        expect_status(port, b"HELO")
        port.write(manifest)
        port.flush()
        announced_size = expect_status(port, b"HEAD")
        if announced_size != len(image):
            raise RuntimeError("Bootloader announced a different image length")
        print("Manifest signature accepted; erasing application sectors...")
        expect_status(port, b"ERAS")

        offset = 0
        while offset < len(image):
            payload = image[offset:offset + CHUNK_SIZE]
            packet = struct.pack(
                "<IIHHI",
                CHUNK_MAGIC,
                offset,
                len(payload),
                0,
                zlib.crc32(payload) & 0xFFFFFFFF,
            ) + payload
            port.write(packet)
            port.flush()
            next_offset = expect_status(port, b"NEXT")
            if next_offset > len(image):
                raise RuntimeError("Bootloader returned an impossible offset")
            offset = next_offset
            print(f"\r{offset * 100 // len(image):3d}%  {offset}/{len(image)} bytes", end="", flush=True)

        version = expect_status(port, b"DONE")
        print(f"\nUpdate verified and committed. Firmware version {version}; device is rebooting.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    keygen = subparsers.add_parser("keygen", help="generate a signing key and C public-key header")
    keygen.add_argument("--private-key", required=True)
    keygen.add_argument("--public-header", required=True)
    keygen.add_argument(
        "--no-password",
        action="store_true",
        help="store an unencrypted development key (keep it outside the repository)",
    )
    keygen.set_defaults(func=command_keygen)

    pack = subparsers.add_parser("pack", help="sign a relocated application binary")
    pack.add_argument("--bin", required=True)
    pack.add_argument("--version", required=True, type=int)
    pack.add_argument("--private-key", required=True)
    pack.add_argument(
        "--no-password",
        action="store_true",
        help="load an unencrypted development key without prompting",
    )
    pack.add_argument("--output", required=True)
    pack.set_defaults(func=command_pack)

    factory = subparsers.add_parser(
        "factory", help="create one first-install HEX containing bootloader and signed app"
    )
    factory.add_argument("--boot-hex", required=True)
    factory.add_argument("--bin", required=True)
    factory.add_argument("--version", required=True, type=int)
    factory.add_argument("--private-key", required=True)
    factory.add_argument(
        "--no-password",
        action="store_true",
        help="load an unencrypted development key without prompting",
    )
    factory.add_argument("--output", required=True)
    factory.set_defaults(func=command_factory)

    apphex = subparsers.add_parser(
        "apphex", help="create a HEX containing signed manifest and app, without bootloader"
    )
    apphex.add_argument("--bin", required=True)
    apphex.add_argument("--version", required=True, type=int)
    apphex.add_argument("--private-key", required=True)
    apphex.add_argument(
        "--no-password",
        action="store_true",
        help="load an unencrypted development key without prompting",
    )
    apphex.add_argument("--output", required=True)
    apphex.set_defaults(func=command_apphex)

    inspect = subparsers.add_parser("inspect", help="validate and display a package")
    inspect.add_argument("package")
    inspect.set_defaults(func=command_inspect)

    send = subparsers.add_parser("send", help="send a package over the KT6328 serial link")
    send.add_argument("--port", required=True, help="Windows COM port, for example COM7")
    send.add_argument("package")
    send.set_defaults(func=command_send)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    args.func(args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
